version: '3'
services:
    nginx: # js file distributing: local development only
        image: nginx:1.19.0
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./frontend/dist/:/usr/share/nginx/js/:ro
        ports: 
            - 8000:80
        depends_on:
            - app
    app:
        build:
            dockerfile: Dockerfile.devel
            context: .
            args: 
                - OPENJDK_TAG=8u232
                - SBT_VERSION=1.4.5 # check out project/build.properties
        command: sbt "~jetty:start"
        depends_on:
            - db
        volumes: 
            - ~/.ivy2:/root/.ivy2
            - ~/.sbt:/root/.sbt
            - .:/app
        working_dir: /app
        ports: 
            - 8080:8080
    db:
        image: mysql:8.0.22
        volumes:
            - ./tmp/db:/var/lib/mysql
            - ./db:/db
        ports:
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=my-secret-pw
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
